image:
  repository: nginx
  tag: stable
  pullPolicy: OnFailure
imagePullSecrets:
  - name: gitlab-docker-secret
configMapRef: []
secretRef: []

schedule: "*/1 * * * *"
args: []

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
